spring.application.name=GScienceAI

server.port=
server.address=0.0.0.0

#######################################################################
# Enable upload big file
#######################################################################
# Set limits to handle multiple gigabytes (e.g., up to 5 Gigabytes)
spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB

# Optional: Ensure your embedded Tomcat chunk buffer size is optimized
server.tomcat.max-http-form-post-size=50000000

#######################################################################
# actuator
#######################################################################
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

#######################################################################
# ImageClassifier
#######################################################################
data.path.base=/home/mgerrit2/dev-ubuntu/software-projects-ubuntu/data/yelp-restaurant-photo-classification
data.path.csv.train=/train/train.csv
data.path.csv.train_photo_to_biz_ids=/train_photo_to_biz_ids.csv/train_photo_to_biz_ids.csv
data.path.csv.train.photo=/train_photos/train_photos
data.path.csv.test.photo.to.biz=/test_photo_to_biz.csv/test_photo_to_biz.csv
data.path.csv.test.photo=/test_photos/test_photos
data.path.csv.result.kaggle=/home/mgerrit2/dev-ubuntu/software-projects-ubuntu/data/results
data.path.base.model.result=results/models/

#######################################################################
# General predefined model
#######################################################################
data.path.base.predefined.model=/home/mgerrit2/dev-ubuntu/software-projects-ubuntu/data/model/predefined/vgg16_imagenet.zip

#######################################################################
# transfur learning
#######################################################################
data.path.dog.versus.cat=/home/mgerrit2/dev-ubuntu/software-projects-ubuntu/data/DoG_CaT
data.path.dog.versus.cat.train=/train
data.path.dog.versus.cat.test=/test
data.path.dog.versus.cat.save="/saved/modelIteration_"



#######################################################################
# SWAGGER
#######################################################################
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
# Standard redirect route
springdoc.swagger-ui.path=/swagger-ui.html


#######################################################################
# zfnet512-12.onnx
#######################################################################
data.path.onnx.zfnet512-12.onnx=/home/mgerrit2/dev-ubuntu/software-projects-ubuntu/data/model/predefined/onnx/zfnet512-12.onnx